In [1]:
import numpy as np

In [2]:
arr_1d=np.array([1,2,3,4,5])
arr_app=np.append(arr_1d,[6,7,8,9,0])
print(arr_app)

[1 2 3 4 5 6 7 8 9 0]


In [5]:
arr_2d=np.array([[1,2,3],[4,5,6]])
arr_2a=np.append(arr_2d,[[7,8,9]],axis=0)
print(arr_2a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
