# syntax
np.delete(array,index,axis=None)

In [1]:
import numpy as np

In [20]:
arr_1d=np.array([1,2,3,4])
print(f"{arr_1d}")
arr_1d_d=np.delete(arr_1d,1,axis=None)
print(arr_1d_d)

[1 2 3 4]
[1 3 4]


In [24]:
arr_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)
arr_2d_d=np.delete(arr_2d,0,axis=1)
print(arr_2d_d)

[[1 2 3 4]
 [5 6 7 8]]
[[2 3 4]
 [6 7 8]]
