In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(np.vstack((arr1,arr2))) #vertically stacking


[[1 2 3]
 [4 5 6]]


In [3]:
print(np.hstack((arr1,arr2))) # horizantal stacking

[1 2 3 4 5 6]
