In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])

In [3]:
print(a)

[1 2 3 4 5]


MAKES EVERY MATRIX TO ZERO

In [4]:
b=np.zeros((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


MAKES EVERY MATRIX TO ONES

In [5]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


IT IS IDENTITY MATRIX

In [6]:
a=np.eye((3))
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


IT IS LIKE A RANGE FUNCTION

In [7]:
a=np.arange(0,10,2)
print(a)

[0 2 4 6 8]


IT DIVIDES THE GIVE RANGE IN N EQUAL PARTS

In [8]:
a=np.linspace(0,1,5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


IT SAYS IF IT IS ONE DIMENSION OR MULTI DIMEMSION

In [9]:
a=np.array([[2,3,4],[6,7,8]])
a.shape

(2, 3)

IT GIVES HOW MUCH ELEMETS ARE PRESENT 

In [10]:
a=np.array([[2,3,4],[6,7,8]])
a.size

6

In [ ]:
a_1d=np.array([1,2,3])
print(a_1d.ndim)
a_2d=np.array([[1,2,3],[4,5,6]])
print(a_2d.ndim)
a_3d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a_3d.ndim)


1


3

type of array

In [17]:
arr=np.array([1.6,2,3])
arr.dtype

dtype('float64')

TYPE CONVERSION

In [25]:
arr=np.array([1.5,3,5.6])
print(arr.dtype)
arr_int=arr.astype(int)
print(arr_int)
print(arr_int.dtype)
arr_str=arr.astype(str)
print(arr_str)
print(arr_str.dtype)


float64
[1 3 5]
int64
['1.5' '3.0' '5.6']
<U32


# MATHEMATICAL OPERATIONS

In [28]:
ab=np.array([1,2,3])
print(ab+5)
print(ab-5)
print(ab*5)
print(ab**5)

[6 7 8]
[-4 -3 -2]
[ 5 10 15]
[  1  32 243]


# AGGREGATE FUNCTION

In [32]:
#sum
arr=np.array([10,20,30])
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))

60
20.0
10
30
8.16496580927726
66.66666666666667
